import { Inter, Lilita_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const lilitaOne = Lilita_One({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lilitaOne.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
